[package]
name = "creepypasta"
description = "force the resolution of a future, or panic"
repository = "https://github.com/withoutboats/creepypasta"
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["Without Boats <woboats@gmail.com>"]
edition = "2018"

[dependencies]
async-task = "1.3.1"
